apiVersion: apps/v1
kind: Deployment
metadata:
 name: db
 namespace: backend
spec:
 selector:
   matchLabels:
     appdb: db
 replicas: 1
 template:
   metadata:
     labels:
       appdb: db
   spec:
     containers:
     - name: db
       image: mongo:3.3
       env:
       - name: MONGODB_DATABASE
         value: testdata
       ports:
       - containerPort: 27017
 
---
 
apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: backend
 labels:
   app: db
spec:
 ports:
 - port: 27017
   protocol: TCP
 selector:
   appdb: db